---
- name: User_script
  hosts: all
  remote_user: ubuntu
  become: yes
  gather_facts: True
  pre_tasks:
    - name: Install python for Ansible
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - name: Add Docker GPG key
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg
      sudo: yes
    - name: Add Docker APT repository
      apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    - name: Install list of packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - docker-ce
      sudo: yes
    - name: Start Docker service
      raw: service docker start
    - name: Install the backend video server
      docker_container:
        name: rtmp-server
        image: antongulenko/rtmp-nginx-server
        pull: yes
        ports:
          # The container ports are hardcoded because they cannot be configured
          - "8080"
          #- "{{ rtmp.port }}:1935"		
    - name: anamoly-injector-agent
      raw: docker run -d --net="host" --pid="host" --privileged teambitflow/anomaly-injector-agent -host=wally166 -api-port 7999